function CC = Curvature(G_graph)
%
% Input:  G_graph, the graph structure generated by Matlab function 'G=graph()'.
% Output: CC: Curvature Centrality
% Reference: O. Knill, “On index expectation and curvature for networks,” 
%           arXiv preprint arXiv:1202.4514, 2012.
% 
% Author: Zelin, Terrence
% Use extra function: fvector3.m and getfacenumber3 (created by Terrence)

node_number = numnodes(G_graph);
CC = zeros(node_number,1);


for index = 1:node_number
    neigh = neighbors(G_graph, index);
    if isempty(neigh)
%         disp('empty');
        CC(index) = 1;
        continue;
    end
    % get subgraph
    sub_graph = subgraph(G_graph, neigh);
    A = adjacency(sub_graph);
    adj_matrix = full(A); % possible that neighbors are not connect to each other
    clique_array = fvector3(adj_matrix);
%     disp(clique_array);
    for vclique_index = 1:length(clique_array)
        vclique = clique_array(vclique_index);
        for temp2 = 1:vclique
            CC(index) = CC(index) + (-1)^(temp2-1) * (vclique)/(temp2);
        end
    end
    
    
    
end
% disp(CC');
end

