function DD_value = DegreeDistance(G_graph, dist_thres)
% Input:  G_graph, the graph structure generated by Matlab function 'G=digraph()'.
%         dist_thres:  distance threshold (set dist_thres = 4 in
%         test)(adjust to find best value)
% Output: M_value: ModularityoutputArg1 = inputArg1;
% 
% Author: Zelin Wan
% Reference: A. Sheikhahmadi, M. A. Nematbakhsh, and A. Shokrol- lahi, 
%           “Improving detection of influential nodes in com- plex networks,”
%           Physica A: Statistical Mechanics and its Applications


node_number = numnodes(G_graph);

% degree_all = indegree(G_graph) + outdegree(G_graph);
degree_all = degree(G_graph);


% degree_all(1) = [];
% disp(degree_all');


S = [];

for i = 1:node_number
    [~, s_p] = max(degree_all);
%     disp('here');
%     disp(max_value);
%     disp(s_p);
    Sel = true;
    
    S_size = size(S);
    for v = 1:S_size
        path = shortestpath(G_graph, s_p, v);
        [~,distance] = size(path);
        
        if distance < dist_thres
            Sel = false;
            break;
        end
%         disp(['distance', int2str(distance)]);
    end
    
    if Sel
        S = [S, s_p];
    end
    degree_all(s_p) = -1;
    
    if length(S) >= 10  % set the max S size
        break;
    end
end

% disp(length(S));

DD_value = S;
% if isempty(size(S))
%     DD_value = 0;
% else
%     DD_value = size(S);
% end
% disp(DD_value);

end

