function DBGC = Degree_based_GC(G_graph)
% Input:  G_graph, the graph structure generated by Matlab function 'G=digraph()'.
% Output: DBGC: Degree based graph centrality

% Author: Zelin Wan
% Reference: J. Nieminen, “On the centrality in a graph,” Scandina- vian 
%               Journal of Psychology, vol. 15, no. 1, pp. 332–336, 1974.

node_number = numnodes(G_graph);

% in_degree = indegree(G_graph);
% out_degree = outdegree(G_graph);
% 
% total_degree = in_degree + out_degree;
total_degree = degree(G_graph);
% disp(total_degree');

max_degree = max(total_degree);
% disp(max_degree);
DBGC = 0;
for i = 1:node_number
    DBGC = DBGC + ((max_degree - total_degree(i))*(1 + max_degree - total_degree(i))/2);
end
DBGC = DBGC/(node_number^2-3*node_number+2);

end