function FFSC = Forwardable_farness_score_old(G_graph,graph_matrix)
% Input:  G_graph, the graph structure generated by Matlab function 'G=graph()'.
%           graph_matrix: adjacency matrix
% 
% Output: FFSC: Forwardable farness score centrality
% 
% Author: Zelin Wan
% 
% Reference:    A. E. Sariyüce, K. Kaya, E. Saule, and U. V. Çatalyürek, 
%               “Graph manipulations for fast centrality computation,” ACM 
%               Transactions on Knowledge Discovery from Data, vol. 11, no. 
%               3, pp. 1–25, Apr. 2017.
 
node_number = length(graph_matrix);

FFSC = zeros(node_number,1);

skip_graph = graph_matrix * ones(node_number,1) + graph_matrix' * ones(node_number,1);

all_nodes_dist = distances(G_graph);
% disp('pre calc finish');

for node_index_u = 1:node_number
    if skip_graph(node_index_u) == 0        % skip deleted node for save time
        continue;
    end 
    for node_index_v = 1:node_number
        if skip_graph(node_index_v) == 0        % skip deleted node for save time
            continue;
        end 
        if all_nodes_dist(node_index_u, node_index_v) ~= inf
            FFSC(node_index_u) = FFSC(node_index_u) + all_nodes_dist(node_index_u, node_index_v);
        end
        
    end
    
end

% disp(FFSC');

end

