function FFSC = Forwardable_farness_score(G_graph)

% Input:  G_graph, the graph structure generated by Matlab function 'G=graph()'.
%           graph_matrix: adjacency matrix
% 
% Output: FFSC: Forwardable farness score centrality
% 
% Author: Zelin Wan
% 
% Reference:    A. E. Sariyüce, K. Kaya, E. Saule, and U. V. Çatalyürek, 
%               “Graph manipulations for fast centrality computation,” ACM 
%               Transactions on Knowledge Discovery from Data, vol. 11, no. 
%               3, pp. 1–25, Apr. 2017.

dst = distances(G_graph);
dst(isinf(dst)) = 0;

FFSC = 1./(dst * (ones(numnodes(G_graph),1)));

% FFSC = 1./FF;
% disp(FFSC');
end