function GDSPDC = GDSP_degree(G_graph, alpha)
%   
%   Input:  G_graph, the graph structure generated by Matlab function 'G=graph()'.
%           graph_matrix: adjacency matrix
%           alpha (alpha = 1.5 in test)
%   Output: GDSPDC: Generalized degree and shortest paths degree
%   Author: Zelin Wan
%   Reference: T. Opsahl, F. Agneessens, and J. Skvoretz, “Node centrality 
%               in weighted networks: Generalizing degree and shortest paths,”
%               Social networks, vol. 32, no. 3, pp. 245–251, 2010.
% 
%              https://www.mathworks.com/help/matlab/ref/graph.centrality.html
%   
% 
% Note: G_graph must have Weight attribute on Edge. Otherwise, error may occur.


wdc = centrality(G_graph, 'degree', 'Importance', G_graph.Edges.Weight);

un_wdc = centrality(G_graph, 'degree');

GDSPDC = (un_wdc.^(1-alpha)) .* (wdc.^alpha);





end

