function LBC = local_betweenness_old(G_graph)
% 
%	Input:  G_graph, the graph structure generated by Matlab function 'G=graph()'.
% 
%   Output: LBC: Local betweenness centrality
% 
%   Author: Zelin Wan
% 
%   Reference:
%               Gao, Shuai, et al. 
%               "Ranking the spreading ability of nodes in complex networks based on local structure." 
%               Physica A: Statistical Mechanics and its Applications 403 (2014): 130-147.



node_number = numnodes(G_graph);
G_matrix = full(adjacency(G_graph));
LBC = zeros(node_number,1);
neighbor_cell = {};

for index = 1:node_number
    neighbor_cell{index} = nonzeros(G_matrix(index,:).*[1:node_number]);
end



for v = 1:node_number          % loop all nodes v
%     disp(['LB working: ' int2str(v)]);
    v_neigh = neighbor_cell{v};        % get neighbor nodes of v
%     disp([v_neigh(1) result(1,1)]);
    % Gamma_1(v)
    
    gamma_1_sum = 0;
    for u = 1:length(v_neigh)              % riemann sum u ∈ Γ(v)    
        
        u_neigh = neighbor_cell{v_neigh(u)};    % get neighbor nodes of u

        gamma_2_sum = 0;                    % Q(u)
        for w = 1:length(u_neigh)           % riemann sum w ∈ Γ(u)
            
                % d2(w) start:
            gamma_2_nearest_neighbor = neighbor_cell{u_neigh(w)};
            gamma_2_next_nearest_neighbor = [];         % get next nearest neighbor
            for nearest_neigh_index = 1:length(gamma_2_nearest_neighbor)
                gamma_2_temp_neighbor = neighbor_cell{gamma_2_nearest_neighbor(nearest_neigh_index)};
                gamma_2_next_nearest_neighbor = [gamma_2_next_nearest_neighbor; gamma_2_temp_neighbor];
            end
            d2w_uniq_nodes = unique([gamma_2_nearest_neighbor; gamma_2_next_nearest_neighbor]);      % remove duplicate nodes
            d2w = length(d2w_uniq_nodes);

            % d2(w) end;
            
            gamma_2_sum = gamma_2_sum + d2w;
        end
        
        gamma_1_sum = gamma_1_sum + gamma_2_sum;
        
    end
    
    LBC(v) = gamma_1_sum;
    
end
%     disp(LBC)    

    

end

