function LA = Local_Assortativity(G_graph)
% Input:  G_graph, the graph structure generated by Matlab function 'G=digraph()'.
% Output: LA: Local Assortativity
% 
% Author: Zelin Wan
% Reference: M. Piraveenan, M. Prokopenko, and A. Y. Zomaya, “Local 
%           assortativeness in scale-free networks,” EPL (Europhysics Letters),
%           vol. 89, no. 4, p. 49901, 2010.


node_number = numnodes(G_graph);
exc_degree_j = ones(node_number, 1);

exc_degree_j = degree(G_graph) - exc_degree_j;
disp('size');
disp(exc_degree_j);

if size(exc_degree_j, 1) == 1           % one node can not create probability distribution
    disp('here');
    LA = 0;
    return;
end

average_exc_k = sum(exc_degree_j)/node_number;

pd = fitdist(exc_degree_j,'Normal');
disp(pd);

mu_q = mean(pd);
sigma_q = std(pd);
edge_num_L = numedges(G_graph);

LA = 0;

for i = 1:node_number
    LA = LA + ((exc_degree_j(i) + 1) * (exc_degree_j(i)*average_exc_k-mu_q^2)) / (2*edge_num_L*sigma_q^2);
    
    
    
    
end


end