function LBC = semi_local(G_graph)
% 
%	Input:  G_graph, the graph structure generated by Matlab function 'G=graph()'.
% 
%   Output: LBC: Local betweenness centrality
% 
%   Author: Zelin Wan
% 
%   Reference:
%               Chen, Duanbing, et al. 
%               "Identifying influential nodes in complex networks." 
%               Physica a: Statistical mechanics and its applications 391.4 (2012): 1777-1787.


node_number = numnodes(G_graph);

G_matrix = full(adjacency(G_graph));
G_matrix(G_matrix>1) = 1;

LBC = zeros(node_number,1);
neighbor_cell = {};

for index = 1:node_number
    neighbor_cell{index} = nonzeros(G_matrix(index,:).*[1:node_number]);
end

% disp("pre calc done");


for v = 1:node_number
    v_neighbor = neighbor_cell{v};
    for u=1:length(v_neighbor)
        v_next_neighbor = neighbor_cell{v_neighbor(u)};
        for w = length(v_next_neighbor)
            w_neighbor = neighbor_cell{v_next_neighbor(w)};
            LBC(v) = LBC(v) + length(w_neighbor);
            for w_2 = length(w_neighbor)
                w_next_neghbor = neighbor_cell{w_neighbor(w_2)};
                LBC(v) = LBC(v) + length(w_next_neghbor);
            end
        end
    end
end
end