function VC = Volume(G_graph, h_hop)
%   Input:  G_graph, the graph structure generated by Matlab function 'G=graph()'.
%           h_hop: h-hop distance (in test, I use h_hop = 2)
% 
%   Output: VC: Volume centrality
% 
%   Author: Zelin Wan
%   
%   Reference:  H. Kim and E. Yoneki, “Influential neighbours selection for
%               information diffusion in online social networks,” in 2012 21st
%               International Conference on Computer Communications and 
%               Networks (ICCCN), July 2012, pp. 1–7.
% 
h_hop = h_hop+1;
node_number = numnodes(G_graph);



VC = zeros(node_number, 1);

% all node degree
node_degrees = degree(G_graph);


for node_index = 1:node_number
    h_hop_nodes = nearest(G_graph, node_index, h_hop, 'Method','unweighted');  % h hop nodes
%     disp(length(h_hop_nodes));
    VC(node_index) = sum(node_degrees(h_hop_nodes)); % SUM
    
end

end

